version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=wfmtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8888:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8080:8080"